/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'api.report': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'api.status': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'compile.report': EventHandler<never, never>
    'analyze.content': EventHandler<never, { topic: 'analyze.content'; data: never }>
    'search.web': EventHandler<never, { topic: 'search.web'; data: never }>
    'generate.queries': EventHandler<never, { topic: 'generate.queries'; data: never }>
    'api.start.research': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'research.started'; data: never }>
  }
}